# Generated by Django 5.0.2 on 2024-02-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuCB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenuitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='springmenuitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='summermenuitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='wintermenuitem',
            name='type',
        ),
        migrations.DeleteModel(
            name='AutumnMenuItem',
        ),
        migrations.DeleteModel(
            name='MainMenuItem',
        ),
        migrations.DeleteModel(
            name='SpringMenuItem',
        ),
        migrations.DeleteModel(
            name='SummerMenuItem',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='WinterMenuItem',
        ),
    ]
