# Generated by Django 5.0.2 on 2024-02-27 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuCB', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.CreateModel(
            name='BarMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuCB.type', verbose_name='Тип блюда')),
            ],
        ),
        migrations.CreateModel(
            name='WineMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuCB.type', verbose_name='Тип блюда')),
            ],
        ),
    ]
