# Generated by Django 5.0.2 on 2024-02-28 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuCB', '0006_alter_barmenuitem_options_alter_mainmenuitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Меню')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.AlterField(
            model_name='type',
            name='season',
            field=models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, to='menuCB.menu', verbose_name='Сезон'),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
