# Generated by Django 5.0.2 on 2024-02-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuCB', '0007_menu_alter_type_season_delete_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenuitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Изображение блюда'),
        ),
    ]
