# Generated by Django 5.0.2 on 2024-02-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuCB', '0008_mainmenuitem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='barmenuitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Изображение блюда'),
        ),
        migrations.AddField(
            model_name='summermenuitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Изображение блюда'),
        ),
        migrations.AddField(
            model_name='winemenuitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Изображение блюда'),
        ),
        migrations.AddField(
            model_name='wintermenuitem',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Изображение блюда'),
        ),
    ]
