# Generated by Django 5.0.2 on 2024-02-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuCB', '0009_barmenuitem_img_summermenuitem_img_winemenuitem_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenuitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='type',
            name='season',
        ),
        migrations.RemoveField(
            model_name='summermenuitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='wintermenuitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='winemenuitem',
            name='type',
        ),
        migrations.DeleteModel(
            name='BarMenuItem',
        ),
        migrations.DeleteModel(
            name='MainMenuItem',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='SummerMenuItem',
        ),
        migrations.DeleteModel(
            name='WinterMenuItem',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='WineMenuItem',
        ),
    ]
