# Generated by Django 5.0.2 on 2024-02-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menuCB', '0010_remove_mainmenuitem_type_remove_type_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Меню')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Тип блюда')),
                ('queue_view', models.IntegerField(default=0, verbose_name='Очередь показа на странице')),
                ('season', models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, to='menuCB.menu', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='SummerMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название блюда')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Изображение блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuCB.type', verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Блюдо летнего меню',
                'verbose_name_plural': 'Блюда летнего меню',
            },
        ),
        migrations.CreateModel(
            name='MainMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название блюда')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Изображение блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuCB.type', verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Блюдо основного  меню',
                'verbose_name_plural': 'Блюда основного меню',
            },
        ),
        migrations.CreateModel(
            name='BarMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название блюда')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Изображение блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuCB.type', verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Товар Барной карта',
                'verbose_name_plural': 'Товары барной карты',
            },
        ),
        migrations.CreateModel(
            name='WineMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название блюда')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Изображение блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuCB.type', verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Товар Винной карта',
                'verbose_name_plural': 'Товары винной карты',
            },
        ),
        migrations.CreateModel(
            name='WinterMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название блюда')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='Изображение блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuCB.type', verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Блюдо зимнего меню',
                'verbose_name_plural': 'Блюда зимнего меню',
            },
        ),
    ]
