# Generated by Django 5.0.2 on 2024-02-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuCB', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Тип блюда'),
        ),
    ]
